/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_broadinstitute_gatk_utils_pairhmm_CPPPairHMM */

#ifndef _Included_org_broadinstitute_gatk_utils_pairhmm_CPPPairHMM
#define _Included_org_broadinstitute_gatk_utils_pairhmm_CPPPairHMM
#ifdef __cplusplus
extern "C" {
#endif
#undef org_broadinstitute_gatk_utils_pairhmm_CPPPairHMM_BASE_QUALITY_SCORE_THRESHOLD
#define org_broadinstitute_gatk_utils_pairhmm_CPPPairHMM_BASE_QUALITY_SCORE_THRESHOLD 18L
/*
 * Class:     org_broadinstitute_gatk_utils_pairhmm_CPPPairHMM
 * Method:    initCPP
 * Signature: (Ljava/lang/Class;Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_org_broadinstitute_gatk_utils_pairhmm_CPPPairHMM_initCPP
  (JNIEnv *, jobject ,jclass, jclass);

/*
 * Class:     org_broadinstitute_gatk_utils_pairhmm_CPPPairHMM
 * Method:    doneCPP
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_broadinstitute_gatk_utils_pairhmm_CPPPairHMM_doneCPP
  (JNIEnv *, jobject);

/*
 * Class:     org_broadinstitute_gatk_utils_pairhmm_CPPPairHMM
 * Method:    sendDataAndResiveFromCPP
 * Signature: (IIII[Lorg/broadinstitute/gatk/utils/pairhmm/CPPPairHMM/JNIReadDataHolderClass;[Lorg/broadinstitute/gatk/utils/pairhmm/CPPPairHMM/JNIHaplotypeDataHolderClass;I)[D
 */
JNIEXPORT void JNICALL Java_org_broadinstitute_gatk_utils_pairhmm_CPPPairHMM_sendDataAndResiveFromCPP
  (JNIEnv *, jobject, jint, jint, jint, jint, jobjectArray, jobjectArray, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
