/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_broadinstitute_gatk_utils_pairhmm_CPPPairHMM_JNIHaplotypeDataHolderClass */

#ifndef _Included_org_broadinstitute_gatk_utils_pairhmm_CPPPairHMM_JNIHaplotypeDataHolderClass
#define _Included_org_broadinstitute_gatk_utils_pairhmm_CPPPairHMM_JNIHaplotypeDataHolderClass
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
