/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_broadinstitute_gatk_engine_FPGA_Init */

#ifndef _Included_org_broadinstitute_gatk_engine_FPGA_Init
#define _Included_org_broadinstitute_gatk_engine_FPGA_Init
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_broadinstitute_gatk_engine_FPGA_Init
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_broadinstitute_gatk_engine_FPGA_1Init_init
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif