//
// Created by shawn on 18-3-20.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_broadinstitute_gatk_tools_walkers_haplotypecaller_FastHaplotypeCaller */

#ifndef _Included_org_broadinstitute_gatk_tools_walkers_haplotypecaller_FastHaplotypeCaller
#define _Included_org_broadinstitute_gatk_tools_walkers_haplotypecaller_FastHaplotypeCaller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_broadinstitute_gatk_tools_walkers_haplotypecaller_FastHaplotypeCaller
 * Method:    initializeCfunction
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_broadinstitute_gatk_tools_walkers_haplotypecaller_FastHaplotypeCaller_initializeCfunction
(JNIEnv *, jobject, jstring);

/*
 * Class:     org_broadinstitute_gatk_tools_walkers_cancer_m2_FastMuTect2
 * Method:    recalibrateCmethod
 * Signature: (IZI[B[BII)V
 */
JNIEXPORT jobjectArray JNICALL Java_org_broadinstitute_gatk_tools_walkers_haplotypecaller_FastHaplotypeCaller_recalibrateCmethod
        (JNIEnv *, jobject, jint, jboolean, jint, jbyteArray, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif