/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_broadinstitute_gatk_utils_smithwaterman_BatchSWPairwiseAlignment_OVERHANG_STRATEGY */

#ifndef _Included_org_broadinstitute_gatk_utils_smithwaterman_BatchSWPairwiseAlignment_OVERHANG_STRATEGY
#define _Included_org_broadinstitute_gatk_utils_smithwaterman_BatchSWPairwiseAlignment_OVERHANG_STRATEGY
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
