/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_broadinstitute_gatk_utils_smithwaterman_BatchSWPairwiseAlignment */

#ifndef _Included_org_broadinstitute_gatk_utils_smithwaterman_BatchSWPairwiseAlignment
#define _Included_org_broadinstitute_gatk_utils_smithwaterman_BatchSWPairwiseAlignment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_broadinstitute_gatk_utils_smithwaterman_BatchSWPairwiseAlignment
 * Method:    jniInit
 * Signature: (Lorg/broadinstitute/gatk/utils/smithwaterman/BatchSWPairwiseAlignment/OVERHANG_STRATEGY;Lorg/broadinstitute/gatk/utils/smithwaterman/Parameters;ZLhtsjdk/samtools/Cigar;Lhtsjdk/samtools/CigarElement;Lhtsjdk/samtools/CigarOperator;)V
 */
JNIEXPORT void JNICALL Java_org_broadinstitute_gatk_utils_smithwaterman_BatchSWPairwiseAlignment_jniInit
  (JNIEnv *, jobject, jobject, jobject, jboolean);

/*
 * Class:     org_broadinstitute_gatk_utils_smithwaterman_BatchSWPairwiseAlignment
 * Method:    jniAlign
 * Signature: (Ljava/util/ArrayList;Ljava/util/ArrayList;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_broadinstitute_gatk_utils_smithwaterman_BatchSWPairwiseAlignment_jniAlign
  (JNIEnv *, jobject, jobject, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
