/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_broadinstitute_gatk_utils_smithwaterman_SWPairwiseAlignment_SWPairwiseAlignmentResult */

#ifndef _Included_org_broadinstitute_gatk_utils_smithwaterman_SWPairwiseAlignment_SWPairwiseAlignmentResult
#define _Included_org_broadinstitute_gatk_utils_smithwaterman_SWPairwiseAlignment_SWPairwiseAlignmentResult
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
