/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
#undef Main_RUNTIME
#define Main_RUNTIME 4000LL
#undef Main_SLEEPTIME
#define Main_SLEEPTIME 1000LL
#undef Main_DEFAULTTHREADCOUNT
#define Main_DEFAULTTHREADCOUNT 4L
/*
 * Class:     Main
 * Method:    initFPGA
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Main_initFPGA
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
