/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_broadinstitute_gatk_utils_pairhmm_CUDAPairHMM */

#ifndef _Included_org_broadinstitute_gatk_utils_pairhmm_CUDAPairHMM
#define _Included_org_broadinstitute_gatk_utils_pairhmm_CUDAPairHMM
#ifdef __cplusplus
extern "C" {
#endif
#undef org_broadinstitute_gatk_utils_pairhmm_CUDAPairHMM_BASE_QUALITY_SCORE_THRESHOLD
#define org_broadinstitute_gatk_utils_pairhmm_CUDAPairHMM_BASE_QUALITY_SCORE_THRESHOLD 18L
/*
 * Class:     org_broadinstitute_gatk_utils_pairhmm_CUDAPairHMM
 * Method:    initCUDA
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_broadinstitute_gatk_utils_pairhmm_CUDAPairHMM_initCUDA
  (JNIEnv *, jobject ,jclass, jclass);

/*
 * Class:     org_broadinstitute_gatk_utils_pairhmm_CUDAPairHMM
 * Method:    doneCUDA
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_broadinstitute_gatk_utils_pairhmm_CUDAPairHMM_doneCUDA
  (JNIEnv *, jobject);

/*
 * Class:     org_broadinstitute_gatk_utils_pairhmm_CUDAPairHMM
 * Method:    sendDataToCUDA
 * Signature: (II[Lorg/broadinstitute/gatk/utils/pairhmm/CUDAPairHMM/JNIReadDataHolderClass;[Lorg/broadinstitute/gatk/utils/pairhmm/CUDAPairHMM/JNIHaplotypeDataHolderClass;)V
 */
JNIEXPORT jfloatArray JNICALL Java_org_broadinstitute_gatk_utils_pairhmm_CUDAPairHMM_sendDataAndResiveFromCUDA
  (JNIEnv *, jobject, jint, jint, jint, jint, jobjectArray, jobjectArray);

/*
 * Class:     org_broadinstitute_gatk_utils_pairhmm_CUDAPairHMM
 * Method:    resiveFromCUDA
 * Signature: (II)[D
 */
//JNIEXPORT jfloatArray JNICALL Java_org_broadinstitute_gatk_utils_pairhmm_CUDAPairHMM_resiveFromCUDA
//  (JNIEnv *, jobject, jint &, jint &);

#ifdef __cplusplus
}
#endif
#endif
